[MENFORCER-360] - requireUpperBoundDeps should have option to check for same major version
apache/maven-enforcer pull request #78
Opened 2020-09-09 18:04 UTC by guyv

An option is added to the built-in requireUpperBoundDeps rule to check for same major version (followins semver.org).

So a (transitive) dependency on groupId:artifactId:1.0.0 and on groupId:artifactId:2.0.0 means that we have a conflict.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

2020-10-28 11:10 UTC, elharo reviewed
@rfscholte 

1. In general I think this proposal is reasonable, but there does not seem to be consensus on it yet.
2. Is it important to allow this to be specified for individual dependencies? Major versions might be a big deal in some dependencies and not others.

2020-10-28 11:10 UTC, elharo requested changes
This needs tests.

2020-10-28 12:03 UTC, guyv commented
@elharo regarding 2.: the exclude tag still works :-)

2020-11-04 15:48 UTC, gmshake commented
Cross link the issue https://issues.apache.org/jira/browse/MENFORCER-360

2021-07-14 09:50 UTC, rfscholte commented
I'm going to close this PR because there are conflicts and there are missing tests.

2021-07-14 09:50 UTC, closed without merging

2025-06-14 14:12 UTC, jira-importer commented
Resolve #473

2025-06-14 14:25 UTC, jira-importer commented
Resolve #473